# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NUGET_URL: "https://nuget.devexpress.com/api"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source ${{ env.NUGET_URL }} \
        -n DevExpressFeed \
        -u DevExpress \
        -p ${{ secrets.DEVEXPRESS_NUGET_KEY }} \
        --store-password-in-clear-text
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: dotnet publish
      run: dotnet publish -c Release --no-restore -o ./publish 
